spin_manifest_version = 2

[application]
authors = ["Christoph Voigt <c.voigt@reply.de>"]
description = "This Spin application serves static files"
name = "static-server"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "static-server"

[component.static-server]
source = "./spin_static_fs.wasm"
files = [{ source = "data", destination = "/" }]
