apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spin-redis
  name: spin-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin-redis
  template:
    metadata:
      labels:
        app: spin-redis
    spec:
      runtimeClassName: wasmtime-spin
      containers:
      - image: ghcr.io/liquid-reply/k8s-spin/spin-redis:latest
        name: spin-env-explorer
        command: ["/"]
        env:
        - name: RUNTIME_CONFIG_FILE
          value: "/runtime_config.toml" # for testing purposes this file is part of the image
        # volumeMounts:
        # - name: redis-config
        #   mountPath: /redis/runtime_config.toml
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      # volumes:
      #   - name: redis-config
      #     configMap:
      #       name: runtime-config
---
apiVersion: v1
data:
  runtime_config.toml: |
    [key_value_store.default]
    type = "redis"
    url = "redis://example-2-redis:6379"
kind: ConfigMap
metadata:
  name: runtime-config
