FROM scratch
COPY ./example-2-redis/spin.toml ./spin.toml

# Remove this line once done testing
COPY ./example-2-redis/redis/runtime_config.toml ./runtime_config.toml

COPY ../bin/env_explorer.wasm ./env_explorer.wasm 
