spin_version = "1"
authors = ["Christoph Voigt <c.voigt@reply.de>"]
description = ""
name = "env-explorer"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[variables]
environment = { default = "kubernetes" }

[[component]]
id = "env-explorer"
source = "env_explorer.wasm"
allowed_http_hosts = []
files = [{ source = "redis", destination = "/redis" }]
key_value_stores = ["default"]
[component.config]
environment = "{{ environment }}"
[component.trigger]
route = "/..."
