spin_manifest_version = 2

[application]
authors = ["Christoph Voigt <c.voigt@reply.de>"]
description = "This Spin application shows configs"
name = "env-explorer"
version = "0.1.0"

[variables]
config_value = { required = true }

[[trigger.http]]
route = "/..."
component = "env-explorer"

[component.env-explorer]
source = "./env_explorer.wasm"
key_value_stores = ["default"]
environment = {"API_URL" = "http://envvars:8080/api", "HELLO" = "WORLD", "TEST_IS" = "Working" }
[component.env-explorer.variables]
config_value = "{{ config_value }}"
