spin_manifest_version = 2

[application]
authors = ["Christoph Voigt <c.voigt@reply.de>"]
description = "This Spin application shows configs"
name = "env-explorer"
version = "0.1.0"

[variables]
environment = { default = "kubernetes" }

[[trigger.http]]
route = "/..."
component = "env-explorer"

[component.env-explorer]
source = "./env_explorer.wasm"
key_value_stores = ["default"]
# files = [{ source = "config", destination = "/" }]
[component.env-explorer.variables]
environment = "{{ environment }}"
#cool_var = "{{ cool_var }}"


# [component.config]
# environment = "{{ environment }}"
