apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spin-secret
  name: spin-secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin-secret
  template:
    metadata:
      labels:
        app: spin-secret
    spec:
      runtimeClassName: wasmtime-spin
      containers:
      - image: ghcr.io/liquid-reply/k8s-spin/spin-redis:latest
        name: spin-env-explorer
        command: ["/"]
        env:
          - name: SPIN_VARIABLE_CONFIG_VALUE
            valueFrom:
              secretKeyRef:
                name: spin-password
                key: password
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
      volumes:
        - name: spin-password
          secret:
            secretName: spin-password
